---
- name: This cleans up Lab 6
  hosts: localhost
  become: true
  tasks:
    - name: copy journal config file
      copy:
        src: /root/.journal
        dest: /etc/systemd/journald.conf
        remote_src: yes

    - name: Remove copied file
      file:
        path: /root/.journal
        state: absent
        
    - name: Remove journal directory
      file:
        path: /var/log/journal
        state: absent
        
    - name: Restart journald
      service:
        name: "systemd-journald"
        state: restarted
        
    - name: Remove recentlogs file
      file:
        path: /home/vagrant/recentlogs.txt
        state: absent
