---
- name: This sets up Lesson 8 Topic A Lab
  hosts: localhost
  become: true
  tasks:
    - name: Remove httpd package
      yum:
        name: httpd
        state: absent
        
    - name: Remove mod_ssl package
      yum:
        name: mod_ssl
        state: absent

    - name: Firewall stuff
      firewalld:
        service: https
        permanent: yes
        state: disabled

    - name: Firewall stuff
      firewalld:
        port: 443/tcp
        permanent: yes
        state: disabled

    - name: Firewall stuff
      firewalld:
        service: http
        permanent: yes
        state: disabled

    - name: Firewall stuff
      firewalld:
        port: 80/tcp
        permanent: yes
        state: disabled

    - name: Firewall stuff
      firewalld:
        service: https
        permanent: no
        state: disabled

    - name: Firewall stuff
      firewalld:
        port: 443/tcp
        permanent: no
        state: disabled

    - name: Firewall stuff
      firewalld:
        service: http
        permanent: no
        state: disabled

    - name: Firewall stuff
      firewalld:
        port: 80/tcp
        permanent: no
        state: disabled
