---
- name: This sets up Lab 12
  hosts: localhost
  become: true
  tasks:
    - name: Remove httpd package
      yum:
        name: httpd
        state: absent

    - name: Firewall stuff
      firewalld:
        service: https
        permanent: yes
        state: disabled

    - name: Firewall stuff
      firewalld:
        port: 443/tcp
        permanent: yes
        state: disabled

    - name: Firewall stuff
      firewalld:
        service: http
        permanent: yes
        state: disabled

    - name: Firewall stuff
      firewalld:
        port: 80/tcp
        permanent: yes
        state: disabled

    - name: Firewall stuff
      firewalld:
        service: https
        permanent: no
        state: disabled

    - name: Firewall stuff
      firewalld:
        port: 443/tcp
        permanent: no
        state: disabled

    - name: Firewall stuff
      firewalld:
        service: http
        permanent: no
        state: disabled

    - name: Firewall stuff
      firewalld:
        port: 80/tcp
        permanent: no
        state: disabled

    - name: create web directory
      shell: mkdir -p /var/www/html

    - name: create index file
      shell: echo "You did it!!" > /var/www/html/index.html
