---
- name: This setup copies the network configuration for backup
  hosts: localhost
  become: true
  tasks:
    - name: Remove packages
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - kmod-kvdo
        - vdo
   
    - name: Install Cups package
      yum:
        name: cups
        state: present

    - name: copy repos     
      copy:
        src: /etc/yum.repos.d
        dest: /root/.repos
        remote_src: yes

    - name: Remove repos 
      shell: rm -rf /etc/yum.repos.d/*
